version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: [ "changelog:dependencies" ]
    # Groups are updated together in one pull request
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
      otel-collector:
        patterns:
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
      otel-instrumentation:
        patterns:
          - "go.opentelemetry.io/contrib/instrumentation/*"

  - package-ecosystem: gomod
    directory: "/internal/tools"
    schedule:
      interval: daily
    labels: [ "changelog:dependencies" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "changelog:dependencies" ]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/agent
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/all-in-one
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/anonymizer
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/collector
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/es-index-cleaner
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/es-rollover
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/ingester
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/jaeger
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/query
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/remote-storage
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/tracegen
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /crossdock
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/base
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/debug
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/hotrod
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /plugin/storage/cassandra
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /docker-compose/elasticsearch
    schedule:
      interval: daily
    allow:
      - dependency-name: "docker.elastic.co/elasticsearch/elasticsearch"
        update-types: ["version-update:semver-minor"]
    includeds:
      - /docker-compose/elasticsearch/v7.yml
      - /docker-compose/elasticsearch/v8.yml
  - package-ecosystem: docker
    directory: /docker-compose/opensearch
    schedule:
      interval: daily
    allow:
      - dependency-name: "docker.elastic.co/opensearch/opensearch"
        update-types: ["version-update:semver-minor"]
    includeds:
      - /docker-compose/opensearch/v1.yml
      - /docker-compose/opensearch/v2.yml
  - package-ecosystem: docker
    directory: /docker-compose/kafka-integration-test
    schedule:
      interval: daily
    allow:
      - dependency-name: "bitnami/kafka"
        update-types: ["version-update:semver-minor"]
    includeds:
      - /docker-compose/kafka-integration-test/v3.yml
  - package-ecosystem: docker
    directory: /docker-compose/cassandra
    schedule:
      interval: daily
    allow:
      - dependency-name: "cassandra"
        update-types: ["version-update:semver-minor"]
    includeds:
      - /docker-compose/cassandra/v3.yml
      - /docker-compose/cassandra/v4.yml

