version: '3.8'

services:
  schema-apply:
    image: cassandra-schema
    build: 
      context: .
      dockerfile: plugin/storage/cassandra/Dockerfile
    environment:
      - CQLSH_HOST=localhost
      - CQLSH_PORT=9042
      - TEMPLATE=/cassandra-schema/${SCHEMA_VERSION}.cql.tmpl
      - KEYSPACE=${KEYSPACE}
    network_mode: service:cassandra
    depends_on:
      - cassandra

networks:
  cassandra-net:
    external: true
