version: '3'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_PORT=9160
    networks:
      - cassandra_net

networks:
  cassandra_net:
    driver: bridge
