name: Build all-in-one

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:
  contents: read

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
        - name: v1
          binary: all-in-one
          skip_sampling: false
        - name: v2
          binary: jaeger
          skip_sampling: true

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 1.22.x

    - name: Setup Node.js version
      uses: ./.github/actions/setup-node.js

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

    - name: Define LOCAL_FLAG var if running on a Pull Request
      run: |
        case ${GITHUB_EVENT_NAME} in
          pull_request)
            echo "LOCAL_FLAG=-l" >> ${GITHUB_ENV}
            ;;
          *)
            echo "LOCAL_FLAG=" >> ${GITHUB_ENV}
            ;;
        esac

    - name: Build, test, and publish all-in-one image
      run: |
        bash scripts/build-all-in-one-image.sh \
          ${{ env.LOCAL_FLAG }} \
          -b ${{ matrix.mode.binary }}
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
        # SKIP_SAMPLING is used by integration tests, see https://github.com/jaegertracing/jaeger/issues/5531
        SKIP_SAMPLING: ${{ matrix.mode.skip_sampling }}
