name: CIT Elasticsearch

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  elasticsearch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:

        - major: 7
          distribution: elasticsearch
          jaeger: v1
        - major: 8
          distribution: elasticsearch
          jaeger: v1
        - major: 8

          distribution: elasticsearch
          jaeger: v2
    name: ${{ matrix.version.distribution }} ${{ matrix.version.major }} ${{ matrix.version.jaeger }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 1.22.x

    - name: Install tools
      run: make install-ci

    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
    - name: Run ${{ matrix.version.distribution }} integration tests
      id: test-execution
      run: bash scripts/es-integration-test.sh ${{ matrix.version.distribution }} ${{ matrix.version.major }} ${{ matrix.version.jaeger }}


    - name: Output ${{ matrix.version.distribution }} logs
      run: docker compose -f docker-compose/elasticsearch/v${{matrix.version.major}}.yml logs ${{ steps.test-execution.outputs.cid }}

